# Multi-Step Methods
In these methods we need multiple previous points of the function we want to integrate. i. e. for $s\text{-step}$ we need $f(t_{-s+1},y_{-s+1}) \dots f(t_{0},y_{0})$ to solve for the equation $\dot{y}(t)=f(t,y)$. 

## The Adams-Bashforth Method
It is a multi-step method of solving first order ordinary differential equations. This method is as follows.


First we denote that our *ODE* is given in the following form.

$$ \dot{y} = f(t,y) $$

Assuming we can approximate the function on the *RHS* with interpolating it as a polynomial. Given that we have $s$ points the polynomial will be of the $(s-1)^{st}$ order. The procedure has been done in the following steps.

$$p(t) \approx f(t,y),\quad p(t_{m})=f\bigl(t_{m},y_{m}\bigr)\equiv f_{m} $$

Then we can use the polynomial to get an approximation for the next step.

$$ y_{n+1} = y_{n} + \int_{t_{n}}^{t_{n+1}} f(t,y)\mathrm{d}t\approx y_{n} + \int_{t_{n}}^{t_{n+1}} p(t)\mathrm{d}t $$

The procedure of obtaining the desired polynomial is written step-by-step:


$$ p(t) = \sum_{m=0}^{s} p_{m}f_{n-s+1+m} $$

$$ p_{m}(t) = \prod_{\substack{l=0 \\ l\neq m}}^{s-1} \frac{t-t_{n-s+1+l}}{t_{n-s+1+m}-t_{n-s+1+l}} $$

Then we will use it inthe integral (we integrate both sides of the ode and we get an approximation for $y_{n+1}$)

$$ y_{n+1} = y_{n} + \int_{t_{n}}^{t_{n+1}} f(t,y)\mathrm{d}t\approx y_{n} + \int_{t_{n}}^{t_{n+1}} p(t)\mathrm{d}t = y_{n} + \int_{t_{n}}^{t_{n+1}} \sum_{m=0}^{s-1}p_{m}(t)f_{n-s+1+m}\mathrm{d}t= y_{n} + h\times\sum_{m=0}^{s-1} b_{m}f_{n-s+1+m} $$

The integrals on the RHS of the equation can be reduced to some coefficients . 

$$ b_{m} = \frac{1}{h}\int_{t_{n}}^{t_{n+1}} p_{m}(t)\mathrm{d}t = \frac{1}{h}\int_{t_{n}}^{t_{n+1}} \prod_{\substack{l=0 \\ l\neq m}}^{s-1} \frac{t-t_{n-s+1+l}}{t_{n-s+1+m}-t_{n-s+1+l}}\mathrm{d}t $$


$$ b_{n} = \int_{h\times n}^{h\times(n+1)} \prod_{\substack{l=0 \\ l\neq m}}^{s-1} \frac{h\times\bigl(\frac{t}{h}-(n-s+1+l)\bigr)}{h\times\bigl((n-s+1+m)-(n-s+1+l)\bigr)}\mathrm{d}\frac{t}{h} \\
\frac{t}{h}\equiv \tilde{t}\Rightarrow b_{m} = \int_{n}^{n+1} \prod_{\substack{l=0 \\ l\neq m}}^{s-1} \frac{\tilde{t}-n+s-1-l}{m-l}\mathrm{d}\tilde{t} $$

And the final form of the coefficients of Adams-Bashforth method is calculated as below:

$$ \tilde{t}\equiv \tau + n\Rightarrow b_{m} = \int_{0}^{1} \prod_{\substack{l=0 \\ l\neq m}}^{s-1} \frac{\tau+s-1-l}{m-l}\mathrm{d}\tau $$

So we get our method as:

$$ y_{n+1} = y_{n} + h\times\sum_{m=0}^{s-1} b_{m}f_{n-s+1+m} $$

## The Adams-Moulton Method
It is a multi-step method of solving first order ordinary differential equations. This method is as follows. In this method we also take $f(t_{n+1},y_{n+1})$ into account.


First we denote that our ode is given in the following form.

$$ \dot{y} = f(t,y) $$

We can approximate the function on the *RHS* with interpolating it as a polynomial. Given that we have $s$ points the polynomial will be of the $(s-1)^{st}$ order. The procedure has been done in the following steps.

$$q(t) \approx f(t,y),\quad q(t_{m})=f\bigl(t_{m},y_{m}\bigr)\equiv f_{m} $$

Then we can use the polynomial to get an approximation for the next step.

$$ y_{n+1} = y_{n} + \int_{t_{n}}^{t_{n+1}} f(t,y)\mathrm{d}t\approx y_{n} + \int_{t_{n}}^{t_{n+1}} q(t)\mathrm{d}t $$

The procedure of obtaining the desired polynomial is written step-by-step:


$$ q(t) = \sum_{m=0}^{s} q_{m}f_{n-s+1+m} $$

**NOTE** that this method generates an $s^{th}$ order polynomial, becuase it is using $s+1$ points to interpolate.

$$ q_{m}(t) = \prod_{\substack{l=0 \\ l\neq m}}^{s} \frac{t-t_{n-s+1+l}}{t_{n-s+1+m}-t_{n-s+1+l}} $$

Then we will use it inthe integral (we integrate both sides of the ode and we get an approximation for $y_{n+1}$)

$$ y_{n+1} = y_{n} + \int_{t_{n}}^{t_{n+1}} f(t,y)\mathrm{d}t\approx y_{n} + \int_{t_{n}}^{t_{n+1}} q(t)\mathrm{d}t = y_{n} + \int_{t_{n}}^{t_{n+1}} \sum_{m=0}^{s}q_{m}(t)f_{n-s+1+m}\mathrm{d}t= y_{n} + h\times\sum_{m=0}^{s} c_{m}f_{n-s+1+m} $$

The integrals on the RHS of the equation can be reduced to some coefficients . 

$$ c_{m} = \frac{1}{h}\int_{t_{n}}^{t_{n+1}} q_{m}(t)\mathrm{d}t = \frac{1}{h}\int_{t_{n}}^{t_{n+1}} \prod_{\substack{l=0 \\ l\neq m}}^{s} \frac{t-t_{n-s+1+l}}{t_{n-s+1+m}-t_{n-s+1+l}}\mathrm{d}t $$


$$ c_{n} = \int_{h\times n}^{h\times(n+1)} \prod_{\substack{l=0 \\ l\neq m}}^{s} \frac{h\times\bigl(\frac{t}{h}-(n-s+1+l)\bigr)}{h\times\bigl((n-s+1+m)-(n-s+1+l)\bigr)}\mathrm{d}\frac{t}{h} \\
\frac{t}{h}\equiv \tilde{t}\Rightarrow c_{m} = \int_{n}^{n+1} \prod_{\substack{l=0 \\ l\neq m}}^{s} \frac{\tilde{t}-n+s-1-l}{m-l}\mathrm{d}\tilde{t} $$

And the final form of the coefficients of Adams-Moulton method is calculated as below:

$$ \tilde{t}\equiv \tau + n\Rightarrow c_{m} = \int_{0}^{1} \prod_{\substack{l=0 \\ l\neq m}}^{s} \frac{\tau+s-1-l}{m-l}\mathrm{d}\tau $$

So we get our method as:

$$ y_{n+1} = y_{n} + h\times\sum_{m=0}^{s} c_{m}f_{n-s+1+m} $$

## Adams-Bashforth-Moulton
Obtaining the algebraic equation for $y_{n+1}$ in terms of the other components can be tricky for **Adams-Moulton** method, thus people often use a predictor-corrector method comprised of **Adams-Bashforth** method as the predictor and **Adams-Moulton** method of the same order as the predictor for correcting the answer obtained by the predictor. So the method is as follows:

$$ \tilde{y}_{n+1} = y_{n} + h\times\sum_{m=0}^{s-1} b_{m}f_{n-s+1+m} $$

$$ y_{n+1} = y_{n} + h\times\Bigl(c_{s-1}f(t_{n+1},\tilde{y}_{n+1})+\sum_{m=0}^{s-2} c_{m}f_{n-s+2-m}\Bigr) $$


Where the coefficients are defined as:

$$\forall m \in [0,\dots,s-1],\quad b_{m} = \int_{0}^{1} \prod_{\substack{l=0 \\ l\neq m}}^{s-1} \frac{\tau-n+s-1-l}{m-l}\mathrm{d}\tau $$

and,

$$\forall m \in [1,\dots,s],\quad c_{m} = \int_{0}^{1} \prod_{\substack{l=1 \\ l\neq m}}^{s} \frac{\tau+s-1-l}{m-l}\mathrm{d}\tau $$

or

$$\forall m \in [0,\dots,s-1],\quad c_{m} = \int_{0}^{1} \prod_{\substack{l=0 \\ l\neq m}}^{s-1} \frac{\tau+s-2-l}{m-l}\mathrm{d}\tau $$


In [83]:
import numpy as np
import sympy

s = np.int64(input("Please enter the degree of predictor-corrector method you want to be calculated: "))
m = 1
t = sympy.symbols('t')
P = sympy.Function('P')(t, s, m)
def P(t,s,m):
    res = 1
    for l in range(s):
        if l!= m:
            res*= (t+s-1-l)/(m-l)
    return res
Q = sympy.Function('Q')(t, s, m)
def Q(t,s,m):
    res = 1
    # This loop could be from 1 to s or 0 to s-1, I chose the latter
    for l in range(s):
        if l!= m:
            res*= (t+s-2-l)/(m-l)
    return res

# 'p's are the polynomial interpolations of the predictor
p = sympy.symarray(('p'), shape=s)
b = sympy.symarray(('b'),shape=s)
# 'q's are the polynomial interpolations of the corrector
q = sympy.symarray(('q'), shape=s)
c = sympy.symarray(('c'),shape=s)
bnum = np.zeros(s).reshape((1,s))
bdenom = np.zeros(s).reshape((1,s))
cnum = np.zeros(s).reshape((1,s))
cdenom = np.zeros(s).reshape((1,s))

for m in range(s):
    p[m]=P(t,s,m)
    b[m]=sympy.Rational(sympy.integrate(p[m],[t,0,1]).simplify())
    bnum[0,m] = b[m].numerator
    bdenom[0,m] = b[m].denominator
    q[m]=Q(t,s,m)
    c[m]=sympy.Rational(sympy.integrate(q[m],[t,0,1]).simplify())
    cnum[0,m] = c[m].numerator
    cdenom[0,m] = c[m].denominator


Please enter the degree of predictor-corrector method you want to be calculated:  6


In [84]:
p

array([-t*(-t - 4)*(-t/2 - 3/2)*(-t/3 - 2/3)*(-t/4 - 1/4)/5,
       -t*(-t - 3)*(-t/2 - 1)*(-t/3 - 1/3)*(t + 5)/4,
       -t*(-t - 2)*(-t/2 - 1/2)*(t/2 + 5/2)*(t + 4)/3,
       -t*(-t - 1)*(t/3 + 5/3)*(t/2 + 2)*(t + 3)/2,
       -t*(t/4 + 5/4)*(t/3 + 4/3)*(t/2 + 3/2)*(t + 2),
       (t/5 + 1)*(t/4 + 1)*(t/3 + 1)*(t/2 + 1)*(t + 1)], dtype=object)

In [85]:
b

array([-95/288, 959/480, -3649/720, 4991/720, -2641/480, 4277/1440],
      dtype=object)

In [86]:
q

array([-t*(1/5 - t/5)*(-t - 3)*(-t/2 - 1)*(-t/3 - 1/3)/4,
       -t*(1/4 - t/4)*(-t - 2)*(-t/2 - 1/2)*(t + 4)/3,
       -t*(1/3 - t/3)*(-t - 1)*(t/2 + 2)*(t + 3)/2,
       -t*(1/2 - t/2)*(t/3 + 4/3)*(t/2 + 3/2)*(t + 2),
       (1 - t)*(t/4 + 1)*(t/3 + 1)*(t/2 + 1)*(t + 1),
       t*(t/5 + 4/5)*(t/4 + 3/4)*(t/3 + 2/3)*(t/2 + 1/2)], dtype=object)

In [87]:
c

array([3/160, -173/1440, 241/720, -133/240, 1427/1440, 95/288],
      dtype=object)

In [88]:
bnum

array([[  -95.,   959., -3649.,  4991., -2641.,  4277.]])

In [89]:
bdenom

array([[ 288.,  480.,  720.,  720.,  480., 1440.]])

In [90]:
cnum

array([[   3., -173.,  241., -133., 1427.,   95.]])

In [91]:
cdenom

array([[ 160., 1440.,  720.,  240., 1440.,  288.]])

# Solving a system of equation via Adams-Bashforth and Adams-Bashforth-Moulton method

## The Kuramoto model

It is a special model of coupled phase oscillators. The model is defined in the following form:

$$ \dot{\theta}_{i} = \omega_{i} + \frac{K}{N}\sum_{j=0}^{N} A_{ij}\sin\bigl(\theta_{j}-\theta_{i}\bigr) $$

The dot indicates the derivative with respect to time, the $\omega_{i}$ is the intrinsic frequency of the $i^{th}$ oscillator, $K$ is the coupling constant, $N$ is the number of oscillators and, $A$ is the adjacency matrix.

In [92]:
global ab; global abm
ab = np.zeros(s).reshape((1,s))
abm = np.zeros(s).reshape((1,s))
for i in range(s):
    ab[0,i] = 1.*np.int64(bnum[0,i])/np.int64(bdenom[0,i])
    abm[0,i] = 1.*np.int64(cnum[0,i])/np.int64(cdenom[0,i])


N = np.int64(input("Please enter the number of oscillators: "))
omega0 = np.float64(input("Please enter the frequency of the oscillators: "))
K = np.float64(input("Please enter the coupling constant: "))
dt = np.float64(input("Please enter the time step size: "))

global one_sixth
one_sixth = 1./6
def func(Theta,w0,N,k):
    theta = Theta.reshape((1,N))
    res = np.ones_like(theta)*w0
    for i in range(N):
        res[0,i] += k*np.sum(np.sin(theta[0,:]-theta[0,i]),axis = 0)
    return res

def rk4_step(Theta,w0,N,k,dt):
    rk1 = func(Theta,w0,N,k)
    rk2 = func(Theta + 0.5*dt*rk1,w0,N,k)
    rk3 = func(Theta + 0.5*dt*rk2,w0,N,k)
    rk4 = func(Theta + dt*rk3,w0,N,k)
    res = Theta + one_sixth*(rk1+2*(rk2+rk3)+rk4)
    return res, rk1

def ab_step(dt,Theta_dot_History):
    res = np.dot(ab,Theta_dot_History)*dt
    return res

def abm_step(dt,Theta_dot_History):
    dummy = Theta_dot_History
    for i in range(s-1):
        dummy[i,:] = dummy[i+1,:]
    dummy[s-1,:] = np.dot(ab,Theta_dot_History)*dt
    res = np.dot(abm,dummy)*dt
    return res
    
def initiate_kuramoto(N,omega0,K,dt):
    # Initiating the phases as a splay with random fluctuation
    Theta0 = np.arange(0., 2*np.pi, 2*np.pi/N).reshape((1,N))+np.random.uniform(0.,1.,N).reshape((1,N))*1.0e-010
    Theta = np.zeros_like(Theta0)
    Theta_dot = np.zeros_like(Theta0)
    Theta_History = np.zeros((s,N))
    Theta_dot_History = np.zeros((s,N))
    #Creating the history
    Theta_History[0,:] = Theta0[0,:]
    k = 1.*N/K
    for i in range(s-1):
        Theta_History[i+1,:], Theta_dot_History[i,:] = rk4_step(Theta_History[i,:],omega0,N,k,dt)
    Theta = Theta_History[s-1,:]
    Theta_dot_History[s-1,:] = func(Theta,omega0,N,k)
    Theta_dot = Theta_dot_History[s-1,:]
    return Theta0,Theta,Theta_dot,Theta_History,Theta_dot_History,k

def Kuramoto(Final_Time,N,omega0,K,dt,method):
    Number_of_Steps = np.int64(Final_Time/dt)
    Time = np.linspace(0.,Final_Time,Number_of_Steps+1)
    Re_R = np.zeros(Number_of_Steps+s)
    Im_R = np.zeros(Number_of_Steps+s)
    rho = np.zeros(Number_of_Steps+s)
    global k
    Theta0,Theta,Theta_dot,Theta_History,Theta_dot_History,k = initiate_kuramoto(N,omega0,K,dt)
    for i in range(s):
        Re_R[i] = np.sum(np.cos(Theta_History[i,:]),axis=0)/N
        Im_R[i] = np.sum(np.sin(Theta_History[i,:]),axis=0)/N
    if method=="rk4":
        for i in range(Number_of_Steps):
            Theta, Theta_dot = rk4_step(Theta,omega0,N,k,dt)
            for j in range(s-1):
                Theta_History[j,:] = Theta_History[j+1,:]
                Theta_dot_History[j,:] = Theta_dot_History[j+1,:]
            Theta_History[s-1,:] = Theta
            Theta_dot_History[s-1,:] = Theta       
            Re_R[i+s] = np.sum(np.cos(Theta_History[s-1,:]),axis=0)/N
            Im_R[i+s] = np.sum(np.sin(Theta_History[s-1,:]),axis=0)/N            
    elif method=="ab":
        for i in range(Number_of_Steps):
            Theta = ab_step(dt,Theta_dot_History)
            Theta_dot = func(Theta,omega0,N,k)
            for j in range(s-1):
                Theta_History[j,:] = Theta_History[j+1,:]
                Theta_dot_History[j,:] = Theta_dot_History[j+1,:]
            Theta_History[s-1,:] = Theta
            Theta_dot_History[s-1,:] = Theta       
            Re_R[i+s] = np.sum(np.cos(Theta_History[s-1,:]),axis=0)/N
            Im_R[i+s] = np.sum(np.sin(Theta_History[s-1,:]),axis=0)/N                    
    elif method=="abm":
        for i in range(Number_of_Steps):
            Theta = abm_step(dt,Theta_dot_History)
            Theta_dot = func(Theta,omega0,N,k)
            for j in range(s-1):
                Theta_History[j,:] = Theta_History[j+1,:]
                Theta_dot_History[j,:] = Theta_dot_History[j+1,:]
            Theta_History[s-1,:] = Theta
            Theta_dot_History[s-1,:] = Theta          
            Re_R[i+s] = np.sum(np.cos(Theta_History[s-1,:]),axis=0)/N
            Im_R[i+s] = np.sum(np.sin(Theta_History[s-1,:]),axis=0)/N            
    else:
        print("Invalid Method!!!")
    rho = np.sqrt(np.multiply(Re_R,Re_R)+np.multiply(Im_R,Im_R))
    # phi = np.tan(np.divide(Im_R,Re_R))
    return rho,Re_R,Im_R   

Final_Time = 1000.
method = input("Please enter the integration method: ")
rho,Re_R,Im_R = Kuramoto(Final_Time,N,omega0,K,dt,method)

Please enter the number of oscillators:  12
Please enter the frequency of the oscillators:  10
Please enter the coupling constant:  10.
Please enter the time step size:  0.5
Please enter the integration method:  rk4


In [93]:
rho

array([1.43605276e-11, 7.28203724e-10, 3.69263352e-08, ...,
       4.60765993e-01, 4.08154081e-01, 1.12623650e-01])

In [95]:
np.sum(rho[80006:])/20000

0.0

In [96]:
np.sum(rho)

1081.4356319361536